# Generated by Django 5.2.8 on 2025-11-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='animal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
