# Generated by Django 5.2.8 on 2025-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_alter_sighting_animal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
