# Generated by Django 5.2.8 on 2025-11-23 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species_predicted', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_predicted', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_radius_predicted', models.FloatField(blank=True, null=True)),
                ('full_response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
